"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path):
    """Load simple KEY=VALUE pairs from .env without overriding real env vars."""

    if not path.exists():
        return

    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


def _env(name, default=""):
    return os.environ.get(name, default)


def _env_bool(name, default=False):
    value = _env(name, str(default)).strip().lower()
    return value in {"1", "true", "yes", "on"}


def _env_list(name, default=None):
    value = _env(name, "")
    if not value:
        return default or []

    return [item.strip() for item in value.split(",") if item.strip()]


_load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _env(
    "DJANGO_SECRET_KEY",
    "django-insecure-+r+8pinaupck+0()ptkxuak8km)6giww(ni+ot7u68h4yk4r6w",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "patients.apps.PatientsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "patients.middleware.PublicVisitTrackingMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = _env("DB_ENGINE", "sqlite").strip().lower()
USE_MYSQL = DB_ENGINE in {"mysql", "django.db.backends.mysql"}

if USE_MYSQL:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": _env("MYSQL_DATABASE", _env("DB_NAME", "register_helssa")),
            "USER": _env("MYSQL_USER", _env("DB_USER", "root")),
            "PASSWORD": _env("MYSQL_PASSWORD", _env("DB_PASSWORD", "")),
            "HOST": _env("MYSQL_HOST", _env("DB_HOST", "127.0.0.1")),
            "PORT": _env("MYSQL_PORT", _env("DB_PORT", "3306")),
            "OPTIONS": {"charset": _env("MYSQL_CHARSET", "utf8mb4")},
        }
    }
else:
    SQLITE_NAME = Path(_env("SQLITE_NAME", str(BASE_DIR / "db.sqlite3")))
    if not SQLITE_NAME.is_absolute():
        SQLITE_NAME = BASE_DIR / SQLITE_NAME

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": SQLITE_NAME,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = _env("DJANGO_LANGUAGE_CODE", "fa-ir")

TIME_ZONE = _env("DJANGO_TIME_ZONE", "Asia/Tehran")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = _env("DJANGO_STATIC_URL", "static/")
STATIC_ROOT = BASE_DIR / _env("DJANGO_STATIC_ROOT", "statics")

ANALYTICS_ENABLED = _env_bool("ANALYTICS_ENABLED", True)
ANALYTICS_STORE_RAW_IP = _env_bool("ANALYTICS_STORE_RAW_IP", False)
ANALYTICS_SHOW_RAW_IP_TO_SUPERUSER = _env_bool(
    "ANALYTICS_SHOW_RAW_IP_TO_SUPERUSER", False
)
ANALYTICS_MASK_IPV4_LAST_OCTET = True
ANALYTICS_MASK_IPV6 = True
ANALYTICS_TRACKED_GET_PATHS = tuple(_env_list("ANALYTICS_TRACKED_GET_PATHS", ["/"]))
ANALYTICS_FORM_GET_PATHS = tuple(_env_list("ANALYTICS_FORM_GET_PATHS", ["/"]))
ANALYTICS_VISITOR_COOKIE_NAME = "helssa_vid"
ANALYTICS_VISITOR_COOKIE_MAX_AGE = 60 * 60 * 24 * 365
try:
    VISIT_REPORT_PDF_MAX_EVENTS = int(_env("VISIT_REPORT_PDF_MAX_EVENTS", "1000"))
except (TypeError, ValueError):
    VISIT_REPORT_PDF_MAX_EVENTS = 1000

# Kavenegar SMS settings
KAVENEGAR_API_KEY = _env("KAVENEGAR_API_KEY")
KAVENEGAR_REGISTER_TEMPLATE = _env("KAVENEGAR_REGISTER_TEMPLATE", "register")
KAVENEGAR_DONE_TEMPLATE = _env("KAVENEGAR_DONE_TEMPLATE", "register-done")
try:
    KAVENEGAR_REQUEST_TIMEOUT_SECONDS = float(
        _env("KAVENEGAR_REQUEST_TIMEOUT_SECONDS", "10")
    )
except (TypeError, ValueError):
    KAVENEGAR_REQUEST_TIMEOUT_SECONDS = 10.0
SMS_SEND_ASYNC = _env_bool("SMS_SEND_ASYNC", True)
APK_UPLOAD_FINALIZE_SYNCHRONOUS = _env_bool("APK_UPLOAD_FINALIZE_SYNCHRONOUS", True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
