# Generated by Django 5.2.14 on 2026-07-14 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_alter_visitevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APKUploadJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "در صف"),
                            ("uploading", "در حال آپلود"),
                            ("preparing", "در حال آماده\u200cسازی"),
                            ("completed", "تکمیل شد"),
                            ("failed", "ناموفق"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="نام فایل اصلی"),
                ),
                (
                    "stored_path",
                    models.TextField(blank=True, verbose_name="مسیر ذخیره موقت"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="پیام خطا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پایان"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apk_upload_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "عملیات آپلود APK",
                "verbose_name_plural": "عملیات\u200cهای آپلود APK",
                "ordering": ("-created_at",),
            },
        ),
    ]
